# Generated by Django 4.0.2 on 2022-03-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poboxes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='emails',
            field=models.ManyToManyField(blank=True, to='poboxes.Emails', verbose_name='E-mails'),
        ),
    ]
