# Generated by Django 4.0.2 on 2022-03-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poboxes', '0002_alter_customers_emails'),
    ]

    operations = [
        migrations.CreateModel(
            name='POBoxes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Número')),
                ('block', models.IntegerField(blank=True, verbose_name='Bloco')),
                ('type', models.CharField(choices=[('Simples', 'Simples'), ('Dupla', 'Dupla')], max_length=7, verbose_name='Tipo')),
                ('pib', models.IntegerField(blank=True, verbose_name='PIB')),
                ('extra_key', models.BooleanField(default=False, verbose_name='Chave Reserva')),
                ('active', models.BooleanField(default=True, verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Caixa Postal',
                'verbose_name_plural': 'Caixas Postais',
                'ordering': ['number'],
            },
        ),
        migrations.AddConstraint(
            model_name='poboxes',
            constraint=models.UniqueConstraint(fields=('number',), name='number_constraints'),
        ),
    ]
