# Generated by Django 4.0.2 on 2022-03-18 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poboxes', '0003_poboxes_poboxes_number_constraints'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='poboxes',
            name='number_constraints',
        ),
    ]
