# Generated by Django 4.0.2 on 2022-03-18 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poboxes', '0004_remove_poboxes_number_constraints'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='adresses',
            name='cep_constraints',
        ),
        migrations.RemoveConstraint(
            model_name='customers',
            name='cpf_cnpj_constraints',
        ),
        migrations.RemoveConstraint(
            model_name='emails',
            name='emails_constraints',
        ),
        migrations.RemoveConstraint(
            model_name='phones',
            name='phones_constraints',
        ),
        migrations.AlterField(
            model_name='poboxes',
            name='extra_key',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não'), ('Verificar', 'Verificar')], default='Verificar', max_length=9, verbose_name='Chave Reserva'),
        ),
        migrations.AlterField(
            model_name='poboxes',
            name='type',
            field=models.CharField(choices=[('Simples', 'Simples'), ('Dupla', 'Dupla')], default='Simples', max_length=7, verbose_name='Tipo'),
        ),
        migrations.AddConstraint(
            model_name='adresses',
            constraint=models.UniqueConstraint(fields=('cep',), name='adresses_cep_constraints'),
        ),
        migrations.AddConstraint(
            model_name='customers',
            constraint=models.UniqueConstraint(fields=('cpf_cnpj',), name='customers_cpf_cnpj_constraints'),
        ),
        migrations.AddConstraint(
            model_name='emails',
            constraint=models.UniqueConstraint(fields=('email',), name='emails_email_constraints'),
        ),
        migrations.AddConstraint(
            model_name='phones',
            constraint=models.UniqueConstraint(fields=('number',), name='phones_number_constraints'),
        ),
        migrations.AddConstraint(
            model_name='poboxes',
            constraint=models.UniqueConstraint(fields=('number',), name='poboxes_number_constraints'),
        ),
    ]
