# Generated by Django 4.0.2 on 2022-03-18 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poboxes', '0005_remove_adresses_cep_constraints_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poboxes',
            name='block',
            field=models.IntegerField(blank=True, null=True, verbose_name='Bloco'),
        ),
        migrations.AlterField(
            model_name='poboxes',
            name='pib',
            field=models.IntegerField(blank=True, null=True, verbose_name='PIB'),
        ),
    ]
