# Generated by Django 4.0.2 on 2022-03-19 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poboxes', '0006_alter_poboxes_block_alter_poboxes_pib'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rentals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_validity', models.DateField(verbose_name='Vigência')),
                ('end_validity', models.DateField(verbose_name='Vencimento')),
                ('rent_value', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Valor')),
                ('warned_in', models.DateField(verbose_name='Avisado em')),
                ('sealed_in', models.DateField(verbose_name='Lacrado em')),
                ('expired', models.BooleanField(default=False, verbose_name='Expirado')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='poboxes.customers', verbose_name='Cliente')),
                ('pobox_id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='poboxes.poboxes', verbose_name='Caixa Postal')),
            ],
            options={
                'verbose_name': 'Aluguel',
                'verbose_name_plural': 'Aluguéis',
                'ordering': ['pobox_id'],
            },
        ),
    ]
