# Generated by Django 4.0.2 on 2022-03-21 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poboxes', '0007_rentals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentals',
            name='sealed_in',
            field=models.DateField(blank=True, null=True, verbose_name='Lacrado em'),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='warned_in',
            field=models.DateField(blank=True, null=True, verbose_name='Avisado em'),
        ),
    ]
