# Generated by Django 4.0.2 on 2022-03-21 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poboxes', '0008_alter_rentals_sealed_in_alter_rentals_warned_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentals',
            name='pobox_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='poboxes.poboxes', verbose_name='Caixa Postal'),
        ),
        migrations.AddConstraint(
            model_name='rentals',
            constraint=models.UniqueConstraint(fields=('pobox_id', 'expired'), name='rentals_pobox_id_expired_constraints'),
        ),
    ]
