# Generated by Django 4.0.2 on 2022-03-23 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poboxes', '0009_alter_rentals_pobox_id_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rentals',
            name='rentals_pobox_id_expired_constraints',
        ),
        migrations.AlterField(
            model_name='rentals',
            name='pobox_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='poboxes.poboxes', verbose_name='Caixa Postal'),
        ),
    ]
