# Generated by Django 4.0.2 on 2022-03-31 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phones',
            name='comments',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Observações'),
        ),
    ]
