# Generated by Django 4.0.2 on 2022-03-31 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_phones_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phones',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
    ]
